# Generated by Django 3.0.6 on 2020-05-28 11:11

import django.core.validators
from django.db import migrations, models
import users.managers.userManager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number format must look like '0810-566-3990'", regex='\\d{4}-\\d{3}-\\d{4}')])),
                ('first_name', models.CharField(blank=True, default='first_name', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, default='last_name', max_length=150, null=True)),
                ('business_name', models.CharField(blank=True, default='first_name', max_length=150, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.managers.userManager.UserManager()),
            ],
        ),
    ]
