# Generated by Django 3.0.6 on 2020-05-29 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], default='Monday', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('is_reoccurring', models.BooleanField(default=False)),
                ('reoccurring_frequency', models.PositiveIntegerField(default=1)),
                ('scheduled_days', models.ManyToManyField(related_name='occurs', to='cafeterias.Day')),
                ('vendor', models.ForeignKey(limit_choices_to={'is_vendor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Order Cost')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid')),
                ('outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('NEW', 'New Order'), ('NEW-PURCHASE', 'New Purchase Order'), ('RECEIVED', 'Order Received'), ('READY', 'Order Ready'), ('DELIVERED', 'Order Delivered'), ('CANCEL-REQUESTED', 'Order Cancelling requested'), ('CANCELLED', 'Order Cancelled')], default='NEW', max_length=20)),
                ('payment_status', models.CharField(choices=[('NOT-PAID', 'Not yet paid for'), ('PART-PAID', 'Partly paid for'), ('FULLY-PAID', 'Fully paid for')], default='NOT-PAID', max_length=10)),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'is_vendor': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafeterias.Menu')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafeterias.Order')),
            ],
        ),
    ]
