# Generated by Django 3.0.6 on 2020-06-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_outstanding'),
        ('cafeterias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='scheduled_days',
            field=models.ManyToManyField(related_name='reoccurs', to='cafeterias.Day'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'is_vendor': True}, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_vendor': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='users.User'),
        ),
    ]
